### ISSUE TITLE
NameUse.FindMatches() bug

### ISSUE THREAD

**Issue by boyangwm** [abb-iss/issues#2]
a NameUse in ConditionBlockStatement is not able to find the declaration match if it's declared in the statement.
For example, for(int i; i < 10; i++)  
iNameUse.FindMatches().Any() returns false where iNameUse is a NameUse of i under the expression i++

**Comment by patrickfrancis** [comment]
Moved to https://github.com/abb-iss/SrcML.NET/issues/79
